import type { Category, Product, Review } from "@/types";

const img = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const categories: Category[] = [
  {
    id: "cat_women",
    slug: "femme",
    name: { fr: "Femme", ar: "نساء" },
    description: {
      fr: "Silhouettes contemporaines, coupes précises et matières nobles.",
      ar: "قصّات معاصرة وأقمشة فاخرة لمجموعة نسائية أنيقة.",
    },
    image: img("photo-1490481651871-ab68de25d43d"),
  },
  {
    id: "cat_men",
    slug: "homme",
    name: { fr: "Homme", ar: "رجال" },
    description: {
      fr: "L’essentiel masculin, taillé pour le quotidien et les soirées.",
      ar: "أساسيات رجالية مصممة لليومي والمناسبات.",
    },
    image: img("photo-1617137968427-85924c800a22"),
  },
  {
    id: "cat_shoes",
    slug: "chaussures",
    name: { fr: "Chaussures", ar: "أحذية" },
    description: {
      fr: "Cuir, daim et sneakers sélectionnés pour la ville.",
      ar: "جلود ونماذج حضرية مختارة بعناية.",
    },
    image: img("photo-1549298916-b41d501d3772"),
  },
  {
    id: "cat_accessories",
    slug: "accessoires",
    name: { fr: "Accessoires", ar: "إكسسوارات" },
    description: {
      fr: "Sacs, ceintures et bijoux pour signer une allure.",
      ar: "حقائب وأحزمة ومجوهرات تُكمل الإطلالة.",
    },
    image: img("photo-1590874103328-eac38a941956"),
  },
];

function variant(
  product: string,
  size: string,
  colorFr: string,
  colorAr: string,
  hex: string,
  stock: number,
) {
  return {
    id: `${product}_${size}_${hex.replace("#", "")}`,
    sku: `${product.toUpperCase()}-${size}-${hex.replace("#", "")}`.slice(0, 32),
    size,
    color: { fr: colorFr, ar: colorAr },
    colorHex: hex,
    stock,
  };
}

export const products: Product[] = [
  {
    id: "p_old_money",
    slug: "old-money",
    sku: "Ens",
    name: { fr: "Old money", ar: "Old money" },
    description: {
      fr: "T-shirt polo style Old Money confectionné en coton piqué haut de gamme avec col contrasté. Confort parfait et allure raffinée.",
      ar: "تيشرت بولو ستايل أولد موني (Old Money) عالي الجودة مع ياقة مميزة. قماش قطني مريح وفخم ومثالي للإطلالات الأنيقة اليومية.",
    },
    categoryId: "cat_men",
    price: 1750,
    compareAtPrice: 2500,
    images: [
      { id: "om1", url: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Old money polo", ar: "تيشرت أولد موني" } },
      { id: "om2", url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Old money colors", ar: "ألوان أولد موني" } },
      { id: "om3", url: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Old money detail", ar: "تفاصيل التيشرت" } },
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: [
      { name: { fr: "Blanc", ar: "أبيض" }, hex: "#FFFFFF" },
      { name: { fr: "Marron", ar: "بني" }, hex: "#8B4513" },
      { name: { fr: "Vert Olive", ar: "زيتي" }, hex: "#2E5A36" },
      { name: { fr: "Bleu Nuit", ar: "كحلي" }, hex: "#1B2A4A" },
      { name: { fr: "Noir", ar: "أسود" }, hex: "#111111" },
    ],
    offers: [
      {
        id: "off_1",
        quantity: 1,
        title: { ar: "تيشرت", fr: "1 T-shirt" },
        price: 1750,
        originalPrice: 2500,
      },
      {
        id: "off_2",
        quantity: 2,
        title: { ar: "2 تيشرت", fr: "2 T-shirts" },
        price: 3000,
        originalPrice: 5000,
        badge: { ar: "الأكثر طلباً 🔥", fr: "Populaire" },
      },
      {
        id: "off_3",
        quantity: 3,
        title: { ar: "احصل على 3", fr: "Pack 3 T-shirts" },
        price: 4500,
        originalPrice: 7500,
        badge: { ar: "عرض التوفير 💰", fr: "Économique" },
      },
    ],
    variants: [
      variant("p_old_money", "M", "Blanc", "أبيض", "#FFFFFF", 25),
      variant("p_old_money", "L", "Blanc", "أبيض", "#FFFFFF", 30),
      variant("p_old_money", "XL", "Blanc", "أبيض", "#FFFFFF", 20),
      variant("p_old_money", "XXL", "Blanc", "أبيض", "#FFFFFF", 15),
      variant("p_old_money", "M", "Marron", "بني", "#8B4513", 18),
      variant("p_old_money", "L", "Marron", "بني", "#8B4513", 22),
      variant("p_old_money", "XL", "Marron", "بني", "#8B4513", 14),
      variant("p_old_money", "M", "Vert Olive", "زيتي", "#2E5A36", 20),
      variant("p_old_money", "L", "Vert Olive", "زيتي", "#2E5A36", 25),
      variant("p_old_money", "XL", "Vert Olive", "زيتي", "#2E5A36", 16),
      variant("p_old_money", "M", "Noir", "أسود", "#111111", 30),
      variant("p_old_money", "L", "Noir", "أسود", "#111111", 35),
      variant("p_old_money", "XL", "Noir", "أسود", "#111111", 20),
    ],
    featured: true,
    isNew: true,
    active: true,
    views: 10030,
    rating: 5.0,
    reviewCount: 48,
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "p_pantalon_lin",
    slug: "pantalon-lin",
    sku: "Pnt",
    name: { fr: "Pontalon lin", ar: "بنطلون كتان صيفي" },
    description: {
      fr: "Pantalon en pur lin européen, coupe droite et taille semi-élastique. Fraîcheur et élégance pour toutes occasions.",
      ar: "بنطلون مصنوع من الكتان الطبيعي المريح، بقصة كلاسيكية أنيقة تناسب جميع الإطلالات اليومية والمناسبات.",
    },
    categoryId: "cat_men",
    price: 2000,
    compareAtPrice: 3000,
    images: [
      { id: "pl1", url: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Pantalon lin", ar: "بنطلون كتان" } },
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: { fr: "Beige", ar: "بيج" }, hex: "#E8DCB8" },
      { name: { fr: "Blanc", ar: "أبيض" }, hex: "#FFFFFF" },
      { name: { fr: "Noir", ar: "أسود" }, hex: "#1A1A1A" },
    ],
    offers: [
      { id: "pnt_1", quantity: 1, title: { ar: "قطعة واحدة", fr: "1 Pièce" }, price: 2000, originalPrice: 3000 },
      { id: "pnt_2", quantity: 2, title: { ar: "2 قطع", fr: "2 Pièces" }, price: 3700, originalPrice: 6000, badge: { ar: "الأكثر طلباً", fr: "Populaire" } },
    ],
    variants: [
      variant("p_pantalon_lin", "M", "Beige", "بيج", "#E8DCB8", 47),
      variant("p_pantalon_lin", "L", "Beige", "بيج", "#E8DCB8", 32),
      variant("p_pantalon_lin", "XL", "Beige", "بيج", "#E8DCB8", 20),
    ],
    featured: true,
    isNew: true,
    active: true,
    views: 1519,
    rating: 4.9,
    reviewCount: 36,
    createdAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "p_robe_rope",
    slug: "robe-rope",
    sku: "Rope",
    name: { fr: "Rope", ar: "فستان روب عصري" },
    description: {
      fr: "Robe d'été moderne en tissu léger et fluide, coupe ample et élégante.",
      ar: "روب صيفي بتصميم راقي وقماش ناعم وخفيف، إطلالة متميزة ومريحة.",
    },
    categoryId: "cat_women",
    price: 3800,
    compareAtPrice: 5200,
    images: [
      { id: "rp1", url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Rope", ar: "روب" } },
    ],
    sizes: ["Standard", "XL"],
    colors: [
      { name: { fr: "Rose", ar: "وردي" }, hex: "#FFB6C1" },
      { name: { fr: "Bleu ciel", ar: "أزرق سماوي" }, hex: "#87CEEB" },
    ],
    offers: [
      { id: "rp_1", quantity: 1, title: { ar: "1 فستان", fr: "1 Robe" }, price: 3800, originalPrice: 5200 },
      { id: "rp_2", quantity: 2, title: { ar: "2 فساتين", fr: "2 Robes" }, price: 6900, originalPrice: 10400, badge: { ar: "توفير", fr: "Pack" } },
    ],
    variants: [
      variant("p_robe_rope", "Standard", "Rose", "وردي", "#FFB6C1", 16),
      variant("p_robe_rope", "XL", "Rose", "وردي", "#FFB6C1", 10),
    ],
    featured: true,
    isNew: false,
    active: true,
    views: 27585,
    rating: 4.8,
    reviewCount: 52,
    createdAt: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "p_jacket_oversize",
    slug: "zip-veste-ovrzise",
    sku: "Jacket",
    name: { fr: "Zip Veste Ovrzise", ar: "سترة زيب أوفرسايز" },
    description: {
      fr: "Veste à capuche zippée oversize, molleton lourd et finitions soignées.",
      ar: "جاكيت هودي أوفرسايز بسحاب كامل، خامة قطنية شتوية دافئة وتصميم عصري شبابي.",
    },
    categoryId: "cat_men",
    price: 2600,
    compareAtPrice: 3800,
    images: [
      { id: "jk1", url: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80", alt: { fr: "Zip Veste", ar: "سترة أوفرسايز" } },
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: [
      { name: { fr: "Noir", ar: "أسود" }, hex: "#111111" },
      { name: { fr: "Gris", ar: "رمادي" }, hex: "#888888" },
    ],
    offers: [
      { id: "jk_1", quantity: 1, title: { ar: "1 سترة", fr: "1 Veste" }, price: 2600, originalPrice: 3800 },
      { id: "jk_2", quantity: 2, title: { ar: "2 سترات", fr: "2 Vestes" }, price: 4800, originalPrice: 7600, badge: { ar: "توفير", fr: "Pack 2" } },
    ],
    variants: [
      variant("p_jacket_oversize", "L", "Noir", "أسود", "#111111", 177),
    ],
    featured: true,
    isNew: true,
    active: true,
    views: 8245,
    rating: 4.9,
    reviewCount: 29,
    createdAt: "2026-03-10T10:00:00.000Z",
  },
  {
    id: "p_linen_shirt",
    slug: "chemise-lin-ivoire",
    name: { fr: "Chemise lin ivoire", ar: "قميص كتان عاجي" },
    description: {
      fr: "Chemise en lin européen, col italien et coupe droite. Une pièce respirante, pensée pour les chaleurs d’Alger comme pour les dîners en terrasse.",
      ar: "قميص من الكتان الأوروبي بياقة إيطالية وقصة مستقيمة. قطعة خفيفة مناسبة لصيف الجزائر والأمسيات.",
    },
    categoryId: "cat_women",
    price: 8900,
    compareAtPrice: 11200,
    images: [
      { id: "i1", url: img("photo-1487412720507-e7ab37603c6f"), alt: { fr: "Chemise lin", ar: "قميص كتان" } },
      { id: "i2", url: img("photo-1469334031216-e4b7dbe29b91"), alt: { fr: "Détail chemise", ar: "تفاصيل القميص" } },
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: { fr: "Ivoire", ar: "عاجي" }, hex: "#EFE8DC" },
      { name: { fr: "Noir", ar: "أسود" }, hex: "#1A1A1A" },
    ],
    variants: [
      variant("p_linen_shirt", "XS", "Ivoire", "عاجي", "#EFE8DC", 8),
      variant("p_linen_shirt", "S", "Ivoire", "عاجي", "#EFE8DC", 12),
      variant("p_linen_shirt", "M", "Ivoire", "عاجي", "#EFE8DC", 10),
      variant("p_linen_shirt", "L", "Ivoire", "عاجي", "#EFE8DC", 6),
      variant("p_linen_shirt", "XS", "Noir", "أسود", "#1A1A1A", 4),
      variant("p_linen_shirt", "S", "Noir", "أسود", "#1A1A1A", 9),
      variant("p_linen_shirt", "M", "Noir", "أسود", "#1A1A1A", 7),
      variant("p_linen_shirt", "L", "Noir", "أسود", "#1A1A1A", 5),
    ],
    featured: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 24,
    createdAt: "2026-03-12T10:00:00.000Z",
  },
  {
    id: "p_silk_dress",
    slug: "robe-satin-nuit",
    name: { fr: "Robe satin nuit", ar: "فستان ساتان ليلي" },
    description: {
      fr: "Robe midi en satin stretch, bretelles fines et fente discrète. Tombé fluide, doublure douce.",
      ar: "فستان ميدي من الساتان المرن بأكتاف رفيعة وشق خفيف. انسيابية أنيقة وبطانة ناعمة.",
    },
    categoryId: "cat_women",
    price: 18900,
    images: [
      { id: "d1", url: img("photo-1515886657613-9f3515b0c78f"), alt: { fr: "Robe satin", ar: "فستان ساتان" } },
      { id: "d2", url: img("photo-1539109136881-3be0616adc40"), alt: { fr: "Robe de soirée", ar: "فستان سهرة" } },
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: { fr: "Noir", ar: "أسود" }, hex: "#111111" },
      { name: { fr: "Bordeaux", ar: "بورجوندي" }, hex: "#5C1A2E" },
    ],
    variants: [
      variant("p_silk_dress", "XS", "Noir", "أسود", "#111111", 3),
      variant("p_silk_dress", "S", "Noir", "أسود", "#111111", 7),
      variant("p_silk_dress", "M", "Noir", "أسود", "#111111", 6),
      variant("p_silk_dress", "L", "Noir", "أسود", "#111111", 4),
      variant("p_silk_dress", "S", "Bordeaux", "بورجوندي", "#5C1A2E", 5),
      variant("p_silk_dress", "M", "Bordeaux", "بورجوندي", "#5C1A2E", 5),
    ],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 41,
    createdAt: "2026-02-02T10:00:00.000Z",
  },
  {
    id: "p_wool_coat",
    slug: "manteau-laine-camel",
    name: { fr: "Manteau laine camel", ar: "معطف صوف جمل" },
    description: {
      fr: "Manteau long en laine mélangée, ceinture à nouer et poches plaquées. Une pièce d’hiver structurée.",
      ar: "معطف طويل من مزيج الصوف بحزام جيوب كلاسيكية. قطعة شتوية ببنية واضحة.",
    },
    categoryId: "cat_women",
    price: 32900,
    images: [
      { id: "c1", url: img("photo-1539533018447-63fcce2678e3"), alt: { fr: "Manteau camel", ar: "معطف جمل" } },
      { id: "c2", url: img("photo-1544022613-e87ca75a784a"), alt: { fr: "Manteau long", ar: "معطف طويل" } },
    ],
    sizes: ["S", "M", "L"],
    colors: [{ name: { fr: "Camel", ar: "جملي" }, hex: "#C4A574" }],
    variants: [
      variant("p_wool_coat", "S", "Camel", "جملي", "#C4A574", 4),
      variant("p_wool_coat", "M", "Camel", "جملي", "#C4A574", 6),
      variant("p_wool_coat", "L", "Camel", "جملي", "#C4A574", 3),
    ],
    featured: true,
    isNew: true,
    rating: 4.7,
    reviewCount: 18,
    createdAt: "2026-04-20T10:00:00.000Z",
  },
  {
    id: "p_tailored_trouser",
    slug: "pantalon-tailleur-noir",
    name: { fr: "Pantalon tailleur noir", ar: "بنطلون رسمي أسود" },
    description: {
      fr: "Pantalon à plis, laine stretch, jambe droite. Taille haute, finition italienne.",
      ar: "بنطلون بطيات من الصوف المرن، ساق مستقيمة وخصر مرتفع.",
    },
    categoryId: "cat_women",
    price: 9800,
    images: [
      { id: "t1", url: img("photo-1506629082955-511b1aa562c8"), alt: { fr: "Pantalon tailleur", ar: "بنطلون رسمي" } },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: { fr: "Noir", ar: "أسود" }, hex: "#1C1C1C" }],
    variants: [
      variant("p_tailored_trouser", "XS", "Noir", "أسود", "#1C1C1C", 6),
      variant("p_tailored_trouser", "S", "Noir", "أسود", "#1C1C1C", 11),
      variant("p_tailored_trouser", "M", "Noir", "أسود", "#1C1C1C", 9),
      variant("p_tailored_trouser", "L", "Noir", "أسود", "#1C1C1C", 8),
      variant("p_tailored_trouser", "XL", "Noir", "أسود", "#1C1C1C", 4),
    ],
    featured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 33,
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "p_knit_polo",
    slug: "polo-maille-sable",
    name: { fr: "Polo maille sable", ar: "بولو تريكو رملي" },
    description: {
      fr: "Polo en coton pima, maille fine, boutons nacre. Coupe légèrement ajustée.",
      ar: "بولو من قطن بيما بتريكو ناعم وأزرار صدف. قصة متوسطة الضبط.",
    },
    categoryId: "cat_men",
    price: 7200,
    images: [
      { id: "k1", url: img("photo-1617127365659-c47fa864d8bc"), alt: { fr: "Polo maille", ar: "بولو تريكو" } },
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: { fr: "Sable", ar: "رملي" }, hex: "#D8C3A5" },
      { name: { fr: "Marine", ar: "كحلي" }, hex: "#1B2A4A" },
    ],
    variants: [
      variant("p_knit_polo", "S", "Sable", "رملي", "#D8C3A5", 10),
      variant("p_knit_polo", "M", "Sable", "رملي", "#D8C3A5", 14),
      variant("p_knit_polo", "L", "Sable", "رملي", "#D8C3A5", 12),
      variant("p_knit_polo", "XL", "Sable", "رملي", "#D8C3A5", 7),
      variant("p_knit_polo", "M", "Marine", "كحلي", "#1B2A4A", 9),
      variant("p_knit_polo", "L", "Marine", "كحلي", "#1B2A4A", 8),
    ],
    featured: true,
    isNew: true,
    rating: 4.5,
    reviewCount: 19,
    createdAt: "2026-05-01T10:00:00.000Z",
  },
  {
    id: "p_oxford_shirt",
    slug: "chemise-oxford-blanche",
    name: { fr: "Chemise oxford blanche", ar: "قميص أكسفورد أبيض" },
    description: {
      fr: "Oxford 100 % coton, col boutonné, poignet mousquetaire. Le classique du vestiaire masculin.",
      ar: "أكسفورد قطني بالكامل بياقة بأزرار. كلاسيكية الخزانة الرجالية.",
    },
    categoryId: "cat_men",
    price: 7800,
    images: [
      { id: "o1", url: img("photo-1594938291221-94d7d52c986f"), alt: { fr: "Chemise oxford", ar: "قميص أكسفورد" } },
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: { fr: "Blanc", ar: "أبيض" }, hex: "#F5F5F0" }],
    variants: [
      variant("p_oxford_shirt", "S", "Blanc", "أبيض", "#F5F5F0", 8),
      variant("p_oxford_shirt", "M", "Blanc", "أبيض", "#F5F5F0", 15),
      variant("p_oxford_shirt", "L", "Blanc", "أبيض", "#F5F5F0", 13),
      variant("p_oxford_shirt", "XL", "Blanc", "أبيض", "#F5F5F0", 6),
    ],
    featured: false,
    isNew: false,
    rating: 4.4,
    reviewCount: 27,
    createdAt: "2025-11-20T10:00:00.000Z",
  },
  {
    id: "p_wool_blazer",
    slug: "blazer-laine-charbon",
    name: { fr: "Blazer laine charbon", ar: "بليزر صوف فحمي" },
    description: {
      fr: "Veste deux boutons, épaule naturelle, doublure cupro. Peut se porter ouverte sur un t-shirt ou fermée en tenue de ville.",
      ar: "سترة بزرّين وكتف طبيعي وبطانة كوبرو. تُرتدى مفتوحة أو مغلقة.",
    },
    categoryId: "cat_men",
    price: 24900,
    images: [
      { id: "b1", url: img("photo-1593032465175-481ac7f401a0"), alt: { fr: "Blazer charbon", ar: "بليزر فحمي" } },
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: { fr: "Charbon", ar: "فحمي" }, hex: "#2F2F2F" }],
    variants: [
      variant("p_wool_blazer", "S", "Charbon", "فحمي", "#2F2F2F", 3),
      variant("p_wool_blazer", "M", "Charbon", "فحمي", "#2F2F2F", 7),
      variant("p_wool_blazer", "L", "Charbon", "فحمي", "#2F2F2F", 6),
      variant("p_wool_blazer", "XL", "Charbon", "فحمي", "#2F2F2F", 2),
    ],
    featured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 15,
    createdAt: "2026-01-28T10:00:00.000Z",
  },
  {
    id: "p_selvedge_jean",
    slug: "jean-selvedge-indigo",
    name: { fr: "Jean selvedge indigo", ar: "جينز سيلفيدج نيلي" },
    description: {
      fr: "Denim japonais 14 oz, coupe tapered, bouton cuivre. Se patine avec le temps.",
      ar: "دنيم ياباني 14 أونصة بقصة تايبرد. يكتسب شخصية مع الزمن.",
    },
    categoryId: "cat_men",
    price: 11500,
    images: [
      { id: "j1", url: img("photo-1542272604-787c3835535d"), alt: { fr: "Jean indigo", ar: "جينز نيلي" } },
    ],
    sizes: ["30", "32", "34", "36"],
    colors: [{ name: { fr: "Indigo", ar: "نيلي" }, hex: "#1E3A5F" }],
    variants: [
      variant("p_selvedge_jean", "30", "Indigo", "نيلي", "#1E3A5F", 5),
      variant("p_selvedge_jean", "32", "Indigo", "نيلي", "#1E3A5F", 9),
      variant("p_selvedge_jean", "34", "Indigo", "نيلي", "#1E3A5F", 8),
      variant("p_selvedge_jean", "36", "Indigo", "نيلي", "#1E3A5F", 4),
    ],
    featured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 22,
    createdAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "p_leather_oxford",
    slug: "derbies-cuir-noir",
    name: { fr: "Derbies cuir noir", ar: "دربي جلد أسود" },
    description: {
      fr: "Cuir de veau italien, semelle cuir, construction Goodyear. Entretien facile, allure nette.",
      ar: "جلد عجل إيطالي ونعل جلدي ببناء غوديير. أناقة واضحة.",
    },
    categoryId: "cat_shoes",
    price: 16800,
    images: [
      { id: "s1", url: img("photo-1614252235316-8c704c769259"), alt: { fr: "Derbies cuir", ar: "حذاء دربي" } },
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: { fr: "Noir", ar: "أسود" }, hex: "#101010" }],
    variants: [
      variant("p_leather_oxford", "40", "Noir", "أسود", "#101010", 4),
      variant("p_leather_oxford", "41", "Noir", "أسود", "#101010", 6),
      variant("p_leather_oxford", "42", "Noir", "أسود", "#101010", 8),
      variant("p_leather_oxford", "43", "Noir", "أسود", "#101010", 7),
      variant("p_leather_oxford", "44", "Noir", "أسود", "#101010", 3),
    ],
    featured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 29,
    createdAt: "2026-02-18T10:00:00.000Z",
  },
  {
    id: "p_city_sneaker",
    slug: "baskets-cuir-ecru",
    name: { fr: "Baskets cuir écru", ar: "سنيكرز جلد فاتح" },
    description: {
      fr: "Sneaker minimaliste en cuir nappa, semelle crêpe, doublure cuir. Fabriquée pour la ville.",
      ar: "سنيكرز بسيطة من جلد نابا ونعل كريب. مصممة للمدينة.",
    },
    categoryId: "cat_shoes",
    price: 13500,
    images: [
      { id: "n1", url: img("photo-1549298916-b41d501d3772"), alt: { fr: "Baskets écru", ar: "سنيكرز فاتحة" } },
    ],
    sizes: ["36", "37", "38", "39", "40", "41", "42"],
    colors: [{ name: { fr: "Écru", ar: "فاتح" }, hex: "#EDE6DA" }],
    variants: [
      variant("p_city_sneaker", "36", "Écru", "فاتح", "#EDE6DA", 4),
      variant("p_city_sneaker", "37", "Écru", "فاتح", "#EDE6DA", 6),
      variant("p_city_sneaker", "38", "Écru", "فاتح", "#EDE6DA", 8),
      variant("p_city_sneaker", "39", "Écru", "فاتح", "#EDE6DA", 7),
      variant("p_city_sneaker", "40", "Écru", "فاتح", "#EDE6DA", 9),
      variant("p_city_sneaker", "41", "Écru", "فاتح", "#EDE6DA", 5),
      variant("p_city_sneaker", "42", "Écru", "فاتح", "#EDE6DA", 4),
    ],
    featured: true,
    isNew: true,
    rating: 4.5,
    reviewCount: 36,
    createdAt: "2026-07-02T10:00:00.000Z",
  },
  {
    id: "p_heel_sandal",
    slug: "sandales-talon-noir",
    name: { fr: "Sandales talon noir", ar: "صندل كعب أسود" },
    description: {
      fr: "Sandale à bride, talon 6 cm, cuir lisse. Équilibre entre tenue et confort de marche.",
      ar: "صندل بشريط وكعب 6 سم من الجلد الناعم. توازن بين الأناقة والراحة.",
    },
    categoryId: "cat_shoes",
    price: 9900,
    images: [
      { id: "h1", url: img("photo-1543163521-1bf539c55dd2"), alt: { fr: "Sandales talon", ar: "صندل كعب" } },
    ],
    sizes: ["36", "37", "38", "39", "40"],
    colors: [{ name: { fr: "Noir", ar: "أسود" }, hex: "#0D0D0D" }],
    variants: [
      variant("p_heel_sandal", "36", "Noir", "أسود", "#0D0D0D", 3),
      variant("p_heel_sandal", "37", "Noir", "أسود", "#0D0D0D", 7),
      variant("p_heel_sandal", "38", "Noir", "أسود", "#0D0D0D", 8),
      variant("p_heel_sandal", "39", "Noir", "أسود", "#0D0D0D", 6),
      variant("p_heel_sandal", "40", "Noir", "أسود", "#0D0D0D", 2),
    ],
    featured: false,
    isNew: false,
    rating: 4.3,
    reviewCount: 14,
    createdAt: "2026-04-04T10:00:00.000Z",
  },
  {
    id: "p_suede_loafer",
    slug: "mocassins-daim-taupe",
    name: { fr: "Mocassins daim taupe", ar: "موكاسين شمواه رمادي" },
    description: {
      fr: "Penny loafer en daim, semelle cuir-caoutchouc. Idéal du bureau à la casbah.",
      ar: "لوفر من الشمواه بنعل مختلط. مناسب للمكتب والمدينة.",
    },
    categoryId: "cat_shoes",
    price: 14200,
    images: [
      { id: "l1", url: img("photo-1560769629-975ec94e6a86"), alt: { fr: "Mocassins daim", ar: "موكاسين شمواه" } },
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: { fr: "Taupe", ar: "رمادي دافئ" }, hex: "#8A7A66" }],
    variants: [
      variant("p_suede_loafer", "40", "Taupe", "رمادي دافئ", "#8A7A66", 5),
      variant("p_suede_loafer", "41", "Taupe", "رمادي دافئ", "#8A7A66", 6),
      variant("p_suede_loafer", "42", "Taupe", "رمادي دافئ", "#8A7A66", 7),
      variant("p_suede_loafer", "43", "Taupe", "رمادي دافئ", "#8A7A66", 4),
      variant("p_suede_loafer", "44", "Taupe", "رمادي دافئ", "#8A7A66", 3),
    ],
    featured: false,
    isNew: true,
    rating: 4.4,
    reviewCount: 11,
    createdAt: "2026-06-21T10:00:00.000Z",
  },
  {
    id: "p_leather_tote",
    slug: "cabas-cuir-noir",
    name: { fr: "Cabas cuir noir", ar: "حقيبة جلد أسود" },
    description: {
      fr: "Cabas structuré en cuir pleine fleur, poche intérieure zippée, anse épaule. Capacité réelle pour la journée.",
      ar: "حقيبة منظمة من الجلد الطبيعي مع جيب داخلي. سعة عملية لليوم.",
    },
    categoryId: "cat_accessories",
    price: 21900,
    images: [
      { id: "a1", url: img("photo-1590874103328-eac38a941956"), alt: { fr: "Cabas cuir", ar: "حقيبة جلد" } },
    ],
    sizes: ["U"],
    colors: [{ name: { fr: "Noir", ar: "أسود" }, hex: "#161616" }],
    variants: [variant("p_leather_tote", "U", "Noir", "أسود", "#161616", 9)],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 48,
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "p_silk_scarf",
    slug: "carre-soie-sable",
    name: { fr: "Carré soie sable", ar: "وشاح حرير رملي" },
    description: {
      fr: "Carré 90 × 90 en soie twill, ourlet roulotté main. Motif géométrique discret.",
      ar: "مربع حرير 90×90 بحاشية يدوية ونقشة هندسية هادئة.",
    },
    categoryId: "cat_accessories",
    price: 6500,
    images: [
      { id: "sc1", url: img("photo-1601924994987-69e26d50dc26"), alt: { fr: "Carré soie", ar: "وشاح حرير" } },
    ],
    sizes: ["U"],
    colors: [{ name: { fr: "Sable", ar: "رملي" }, hex: "#C8B59A" }],
    variants: [variant("p_silk_scarf", "U", "Sable", "رملي", "#C8B59A", 18)],
    featured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 9,
    createdAt: "2026-08-11T10:00:00.000Z",
  },
  {
    id: "p_gold_hoops",
    slug: "creoles-dorees",
    name: { fr: "Créoles dorées", ar: "حلق ذهبية" },
    description: {
      fr: "Créoles moyennes en acier doré 18k, fermoir sécurisé. Pièce quotidienne, légère.",
      ar: "حلق متوسطة من الفولاذ المطلي ذهب 18 قيراط. خفيفة لليومي.",
    },
    categoryId: "cat_accessories",
    price: 3900,
    images: [
      { id: "g1", url: img("photo-1611652022419-a73b71080486"), alt: { fr: "Créoles", ar: "حلق" } },
    ],
    sizes: ["U"],
    colors: [{ name: { fr: "Or", ar: "ذهبي" }, hex: "#C5A572" }],
    variants: [variant("p_gold_hoops", "U", "Or", "ذهبي", "#C5A572", 25)],
    featured: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 52,
    createdAt: "2025-12-09T10:00:00.000Z",
  },
  {
    id: "p_leather_belt",
    slug: "ceinture-cuir-noir",
    name: { fr: "Ceinture cuir noir", ar: "حزام جلد أسود" },
    description: {
      fr: "Ceinture 3 cm, cuir tanné végétal, boucle brossée. Taille ajustable.",
      ar: "حزام 3 سم من الجلد المدبوغ نباتياً بإبزيم مصقول.",
    },
    categoryId: "cat_accessories",
    price: 4200,
    images: [
      { id: "be1", url: img("photo-1624222247344-550fb60583c2"), alt: { fr: "Ceinture cuir", ar: "حزام جلد" } },
    ],
    sizes: ["85", "90", "95", "100"],
    colors: [{ name: { fr: "Noir", ar: "أسود" }, hex: "#1A1A1A" }],
    variants: [
      variant("p_leather_belt", "85", "Noir", "أسود", "#1A1A1A", 7),
      variant("p_leather_belt", "90", "Noir", "أسود", "#1A1A1A", 10),
      variant("p_leather_belt", "95", "Noir", "أسود", "#1A1A1A", 8),
      variant("p_leather_belt", "100", "Noir", "أسود", "#1A1A1A", 5),
    ],
    featured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 17,
    createdAt: "2026-02-25T10:00:00.000Z",
  },
  {
    id: "p_watch",
    slug: "montre-acier-ivoire",
    name: { fr: "Montre acier ivoire", ar: "ساعة فولاذ عاجية" },
    description: {
      fr: "Boîtier 36 mm, cadran ivoire, bracelet maille milanaise. Mouvement quartz suisse.",
      ar: "علبة 36 مم بوجه عاجي وسوار ميلانيز. حركة كوارتز سويسرية.",
    },
    categoryId: "cat_accessories",
    price: 18500,
    images: [
      { id: "w1", url: img("photo-1523170335258-f5ed11844a49"), alt: { fr: "Montre acier", ar: "ساعة فولاذ" } },
    ],
    sizes: ["U"],
    colors: [{ name: { fr: "Acier", ar: "فضي" }, hex: "#C0C0C0" }],
    variants: [variant("p_watch", "U", "Acier", "فضي", "#C0C0C0", 6)],
    featured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 21,
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: "p_cashmere_knit",
    slug: "pull-cachemire-grege",
    name: { fr: "Pull cachemire grège", ar: "كنزة كشمير بيج" },
    description: {
      fr: "Col rond, cachemire grade A, coupe relaxed. Une base précieuse du vestiaire.",
      ar: "كنزة بياقة دائرية من كشمير درجة أولى وقصة مريحة.",
    },
    categoryId: "cat_women",
    price: 15900,
    images: [
      { id: "ca1", url: img("photo-1434389677669-e08b4cac3105"), alt: { fr: "Pull cachemire", ar: "كنزة كشمير" } },
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: { fr: "Grège", ar: "بيج" }, hex: "#C5B8A5" }],
    variants: [
      variant("p_cashmere_knit", "XS", "Grège", "بيج", "#C5B8A5", 4),
      variant("p_cashmere_knit", "S", "Grège", "بيج", "#C5B8A5", 8),
      variant("p_cashmere_knit", "M", "Grège", "بيج", "#C5B8A5", 7),
      variant("p_cashmere_knit", "L", "Grège", "بيج", "#C5B8A5", 5),
    ],
    featured: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 13,
    createdAt: "2026-08-28T10:00:00.000Z",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p_silk_dress",
    author: "Amel B.",
    rating: 5,
    comment: {
      fr: "Tombé impeccable, tissu non transparent. Reçue en 48 h à Alger.",
      ar: "القماش ممتاز وغير شفاف. وصلت خلال يومين إلى الجزائر.",
    },
    createdAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "r2",
    productId: "p_silk_dress",
    author: "Sarah K.",
    rating: 5,
    comment: {
      fr: "Coupe fidèle, je prends toujours un M chez Velora.",
      ar: "القصة دقيقة، أختار دائماً مقاس M.",
    },
    createdAt: "2026-06-02T10:00:00.000Z",
  },
  {
    id: "r3",
    productId: "p_leather_tote",
    author: "Nour D.",
    rating: 5,
    comment: {
      fr: "Le cuir est dense, les coutures propres. Un vrai sac de tous les jours.",
      ar: "الجلد متين والخياطة نظيفة. حقيبة يومية ممتازة.",
    },
    createdAt: "2026-05-18T10:00:00.000Z",
  },
  {
    id: "r4",
    productId: "p_linen_shirt",
    author: "Yasmine L.",
    rating: 4,
    comment: {
      fr: "Très belle, un peu ample : prenez une taille en dessous si vous aimez près du corps.",
      ar: "جميلة جداً وواسعة قليلاً. اختاري مقاساً أصغر للقصة الضيقة.",
    },
    createdAt: "2026-04-09T10:00:00.000Z",
  },
  {
    id: "r5",
    productId: "p_city_sneaker",
    author: "Karim M.",
    rating: 5,
    comment: {
      fr: "Confort immédiat, look discret. Paiement à la livraison sans souci.",
      ar: "مريحة من أول يوم ومظهر هادئ. الدفع عند الاستلام تم بسلاسة.",
    },
    createdAt: "2026-07-30T10:00:00.000Z",
  },
  {
    id: "r6",
    productId: "p_wool_blazer",
    author: "Riad H.",
    rating: 5,
    comment: {
      fr: "Épaule naturelle, pas trop cintrée. Qualité au-dessus du prix.",
      ar: "كتف طبيعي وغير ضيق. الجودة أعلى من السعر.",
    },
    createdAt: "2026-03-22T10:00:00.000Z",
  },
];
